### ISSUE TITLE
Please share simulation database

### ISSUE THREAD

**Issue by driofernandes** [jfcrenshaw/donut-sims#1]
Opsim simulation database seems to be required to run the code, but I could not find it online. Could you please share it, or share the code you've used to generate it? Thanks in advance!

`/astro/store/epyc/users/jfc20/rubin_sim_data/sim_baseline/baseline.db`

**Comment by jfcrenshaw** [comment]
I think this page has the info you're looking for
https://rubin-sim.lsst.io/data-download.html#data-download

**Comment by driofernandes** [comment]
Thanks!
